// ---------------------------------------------------------------------------
// Dados de criação de personagem: raças, origens, classes, escolas de magia,
// traços, aparência. Tudo com efeitos MECÂNICOS reais (usados por física,
// combate e pelo Mestre IA na avaliação de plausibilidade).
// ---------------------------------------------------------------------------

export const ATTRS = {
  forca:      { nome: 'Força',       desc: 'Carga máxima, dano corpo-a-corpo, quanto de massa você consegue erguer/arremessar com telecinese física.' },
  destreza:   { nome: 'Destreza',    desc: 'Velocidade, altura do pulo, esquiva, precisão de conjuração à distância.' },
  vigor:      { nome: 'Vigor',       desc: 'Vida máxima, estamina, resistência a frio/calor/veneno e a quedas.' },
  intelecto:  { nome: 'Intelecto',   desc: 'Mana máxima, potência mágica bruta e qualidade dos argumentos aceitos pelo Mestre IA.' },
  espirito:   { nome: 'Espírito',    desc: 'Regeneração de mana, resistência mágica, estabilidade perto do Véu.' },
  carisma:    { nome: 'Carisma',     desc: 'Preços, aliados, e o quanto o Mestre IA concede o benefício da dúvida.' },
};

export const RACES = {
  humano: {
    nome: 'Humano', mods: { forca: 1, destreza: 1, vigor: 1, intelecto: 1, espirito: 1, carisma: 1 },
    altura: [1.55, 1.95], peso: [50, 110], cores: ['#f0c9a4', '#d9a066', '#8d5524', '#5a3317', '#e8b88a'],
    passiva: 'Versátil: +1 em TODOS os atributos, +10% de XP e 1 ponto livre extra por nível.',
    desc: 'Adaptáveis e ambiciosos. Não são os melhores em nada e são competentes em tudo — a única raça que soma em todos os seis atributos. O Mestre IA cobra menos justificativa quando um humano improvisa com ferramentas mundanas.',
    fis: { massaBase: 78, alcance: 1.0, tolFrio: 1.0, tolCalor: 1.0 },
    tags: ['versatil'], visual: {},
  },
  elfo: {
    nome: 'Elfo', mods: { destreza: 3, intelecto: 2, espirito: 1, vigor: -1, forca: -1 },
    altura: [1.7, 2.05], peso: [45, 75], cores: ['#f5e0c8', '#e8d3b0', '#cdbfa0', '#dcc8a8'],
    passiva: 'Graça Élfica: -30% de dano de queda, +15% de precisão à distância, imune a sono mágico.',
    desc: 'Longevos, leves e ligados à trama arcana. Corpos frágeis com reflexos absurdos. A massa baixa é faca de dois gumes: saltam mais alto, mas rajadas de vento e ondas de choque os arremessam longe.',
    fis: { massaBase: 60, alcance: 1.1, tolFrio: 0.9, tolCalor: 1.0 },
    tags: ['queda_suave', 'visao_noturna'], visual: { orelhas: 'pontudas' },
  },
  anao: {
    nome: 'Anão', mods: { vigor: 3, forca: 2, espirito: 1, destreza: -2, carisma: -1 },
    altura: [1.2, 1.5], peso: [65, 110], cores: ['#e0b48c', '#c98d5a', '#9a6b3f', '#d4a070'],
    passiva: 'Pé de Pedra: imune a empurrão e derrubada, +40% de eficiência ao construir, visão no escuro, resistência a veneno.',
    desc: 'Baixos, densos e teimosos como a rocha que mineram. Densidade corporal alta significa inércia alta: quase impossíveis de mover, péssimos em saltos longos. Constroem estruturas que aguentam mais.',
    fis: { massaBase: 90, alcance: 0.8, tolFrio: 1.4, tolCalor: 1.1 },
    tags: ['inabalavel', 'construtor', 'visao_noturna', 'resist_veneno'], visual: { barba: true, atarracado: true },
  },
  halfling: {
    nome: 'Halfling', mods: { destreza: 3, carisma: 2, espirito: 1, forca: -3, vigor: -1 },
    altura: [0.85, 1.1], peso: [18, 32], cores: ['#f0c9a4', '#e8b88a', '#d9a066'],
    passiva: 'Sorte: ao falhar uma rolagem do Mestre IA, você rerrola automaticamente (1× por ação). Passa por vãos que ninguém mais passa.',
    desc: 'Pequenos, alegres e inexplicavelmente afortunados. Massa de ~25 kg os torna os seres mais arremessáveis do mundo — e os melhores em se esconder atrás de absolutamente qualquer coisa.',
    fis: { massaBase: 25, alcance: 0.62, tolFrio: 0.9, tolCalor: 1.0 },
    tags: ['sorte', 'pequeno', 'furtivo'], visual: { atarracado: true, pesLargos: true },
  },
  dragonborn: {
    nome: 'Dragonborn', mods: { forca: 2, carisma: 2, vigor: 1, destreza: -1 },
    altura: [1.8, 2.15], peso: [95, 160], cores: ['#a8332a', '#2f6b8f', '#3f7a45', '#b58a2a', '#6a6a72', '#c0c0cc'],
    passiva: 'Sopro Elemental: cone de dano na cor da sua escama (cooldown longo) e resistência 50% ao próprio elemento.',
    desc: 'Humanoides dracônicos, orgulhosos e de presença esmagadora. A imunidade parcial ao próprio elemento muda a tática: um dragonborn vermelho atravessa o próprio muro de chamas ileso.',
    fis: { massaBase: 115, alcance: 1.12, tolFrio: 1.2, tolCalor: 1.5 },
    tags: ['sopro', 'escamas'], visual: { chifres: true, escamas: true, focinho: true, cauda: true },
  },
  tiefling: {
    nome: 'Tiefling', mods: { carisma: 3, intelecto: 2, espirito: -1 },
    altura: [1.6, 1.95], peso: [52, 100], cores: ['#b04a4a', '#8a3a5a', '#d06a5a', '#6a3a6a', '#c05a3a'],
    passiva: 'Legado Infernal: resistência 50% a fogo, visão no escuro, e o Mestre IA aceita barganhas e intimidação como argumento válido.',
    desc: 'Descendentes de pactos infernais. Chifres, cauda e olhos sem pupila. Socialmente marcados, arcanamente privilegiados: a herança demoníaca os torna imunes ao calor que mataria outros.',
    fis: { massaBase: 76, alcance: 1.02, tolFrio: 1.0, tolCalor: 1.8 },
    tags: ['resist_fogo', 'visao_noturna', 'barganha'], visual: { chifres: true, cauda: true, olhosSemPupila: true },
  },
  meio_orc: {
    nome: 'Meio-Orc', mods: { forca: 3, vigor: 2, intelecto: -1, carisma: -1 },
    altura: [1.8, 2.2], peso: [90, 155], cores: ['#6f8f5a', '#4f7040', '#87a06a', '#9aab7a'],
    passiva: 'Resistência Implacável: ao chegar a 0 de vida, você sobrevive com 1 PV (1× por descanso). Abaixo de 30%: +50% de dano físico.',
    desc: 'Músculo bruto e teimosia herdada dos dois lados. Erguem e arremessam massas que outras raças nem tiram do chão — a capacidade de carga escala diretamente com Força e massa corporal.',
    fis: { massaBase: 112, alcance: 1.15, tolFrio: 1.1, tolCalor: 1.2 },
    tags: ['furia_sangue', 'implacavel'], visual: { presas: true, musculoso: true },
  },
  meio_elfo: {
    nome: 'Meio-Elfo', mods: { carisma: 2, destreza: 1, intelecto: 1, espirito: 1 },
    altura: [1.65, 1.95], peso: [52, 90], cores: ['#f0c9a4', '#e8d3b0', '#d9a066', '#cdbfa0'],
    passiva: 'Herança Dupla: +1 ponto livre extra na criação, visão no escuro, imune a sono mágico e -15% de dano de queda.',
    desc: 'Nem de um mundo nem do outro, e por isso confortáveis em ambos. Diplomatas natos: o Mestre IA concede benefício da dúvida com mais frequência a quem tem Carisma alto.',
    fis: { massaBase: 72, alcance: 1.05, tolFrio: 0.95, tolCalor: 1.0 },
    tags: ['queda_suave', 'visao_noturna', 'versatil'], visual: { orelhas: 'semipontudas' },
  },
  gnomo: {
    nome: 'Gnomo', mods: { intelecto: 3, destreza: 1, espirito: 1, forca: -3, vigor: -1 },
    altura: [0.9, 1.2], peso: [20, 38], cores: ['#f0c9a4', '#e8b88a', '#dcb090'],
    passiva: 'Esperteza Gnômica: +2 de bônus fixo em TODA avaliação do Mestre IA que envolva mecanismos, engenharia ou química. Visão no escuro.',
    desc: 'Pequenos, curiosos e perigosamente inventivos. A raça que mais lucra com o sistema de argumentação: alavancas, polias, pressão e reações são a língua nativa deles.',
    fis: { massaBase: 28, alcance: 0.66, tolFrio: 0.95, tolCalor: 0.95 },
    tags: ['engenhoso', 'pequeno', 'visao_noturna'], visual: { atarracado: true, orelhas: 'pontudas', barba: true },
  },
  tabaxi: {
    nome: 'Tabaxi', mods: { destreza: 3, carisma: 1, espirito: 1, vigor: -1 },
    altura: [1.6, 1.95], peso: [50, 85], cores: ['#d8a860', '#c8925a', '#8a6a48', '#e0c090', '#5a4a40'],
    passiva: 'Reflexos Felinos: NUNCA sofre dano de queda (cai de pé), escala superfícies verticais, +1 m/s de velocidade base.',
    desc: 'Povo felino, nômade e insaciavelmente curioso. A imunidade total a queda reescreve o mapa: penhascos viram atalhos e a verticalidade do terreno deixa de ser ameaça e vira rota.',
    fis: { massaBase: 66, alcance: 1.08, tolFrio: 0.95, tolCalor: 1.15 },
    tags: ['cai_de_pe', 'escalador', 'agil', 'visao_noturna'], visual: { focinho: true, orelhasAnimais: 'felinas', cauda: true, pelagem: true },
  },
  aarakocra: {
    nome: 'Aarakocra', mods: { destreza: 3, espirito: 2, forca: -2, vigor: -2 },
    altura: [1.45, 1.75], peso: [30, 48], cores: ['#8a6a48', '#c0b0a0', '#5a4a3a', '#d8d0c0', '#3a3a42'],
    passiva: 'Voo: mantenha ESPAÇO para planar indefinidamente e ganhe altitude com correntes térmicas. Ossos ocos: -50% de massa efetiva.',
    desc: 'Pássaros humanoides das correntes altas. A única raça com voo real — o que resolve metade dos problemas de terreno e cria outros: 40 kg de massa significa que uma rajada de vento te manda para o próximo bioma.',
    fis: { massaBase: 38, alcance: 1.05, tolFrio: 0.8, tolCalor: 0.95 },
    tags: ['voo', 'cai_de_pe', 'leve'], visual: { asas: true, bico: true, penas: true },
  },
  genasi: {
    nome: 'Genasi', mods: { vigor: 2, intelecto: 1, espirito: 2, carisma: -1 },
    altura: [1.6, 1.95], peso: [55, 105], cores: ['#c04a2a', '#3a8ac0', '#8a7050', '#c0d0e0'],
    passiva: 'Herança Elemental: escolha um elemento (fogo/água/terra/ar). Imune a ele, +40% de dano com a escola correspondente, e -25% de custo de mana dessa escola.',
    desc: 'Ligados ao plano elemental de origem. Um Genasi do Fogo caminha dentro do próprio incêndio; um da Água respira submerso e triplica a hidromancia. O elemento define seu estilo inteiro de jogo.',
    fis: { massaBase: 80, alcance: 1.02, tolFrio: 1.3, tolCalor: 1.3 },
    tags: ['elemental'], visual: { aura: true, veias: true },
    elementos: {
      fogo:  { nome: 'Genasi do Fogo',  cor: '#ff6a2a', escola: 'fogo',  passiva: 'Imune a fogo. Deixa rastro de brasa ao correr.' },
      agua:  { nome: 'Genasi da Água',  cor: '#3aa6ff', escola: 'agua',  passiva: 'Respira submerso, nada na velocidade máxima.' },
      terra: { nome: 'Genasi da Terra', cor: '#b98a4a', escola: 'terra', passiva: 'Imune a empurrão, atravessa rocha lentamente.' },
      ar:    { nome: 'Genasi do Ar',    cor: '#b9e3ff', escola: 'ar',    passiva: 'Plana, imune a dano de queda, não precisa respirar.' },
    },
  },
  goliath: {
    nome: 'Goliath', mods: { forca: 4, vigor: 3, destreza: -2, carisma: -2, intelecto: -1 },
    altura: [2.1, 2.6], peso: [140, 230], cores: ['#9aa0a8', '#8a8a92', '#a8a09a', '#7a8088'],
    passiva: 'Nascido da Montanha: imune a frio e a mal de altitude, capacidade de carga DOBRADA, imune a empurrão.',
    desc: 'Gigantes de pele pétrea das escarpas mais altas. Erguem e arremessam objetos de centenas de quilos — a capacidade de carga dobrada é literalmente o dobro no cálculo do Mestre IA. Em compensação, 200 kg de massa quebram pisos frágeis e tornam saltos patéticos.',
    fis: { massaBase: 190, alcance: 1.3, tolFrio: 2.0, tolCalor: 1.0 },
    tags: ['carga_dobrada', 'inabalavel', 'imune_frio', 'grande'], visual: { musculoso: true, marcasPele: true, pelePetrea: true },
  },
  aasimar: {
    nome: 'Aasimar', mods: { carisma: 3, espirito: 3, forca: -1, destreza: -1 },
    altura: [1.65, 2.0], peso: [55, 100], cores: ['#f8e0c0', '#f0d0b0', '#e8c8a8', '#fff0dc'],
    passiva: 'Chama Interior: resistência 50% a dano radiante e necrótico, curas que você lança curam +30%, e você emite luz própria (dispensa tocha).',
    desc: 'Sangue celestial numa forma mortal. Olhos que brilham e uma presença que desarma. O melhor suporte do jogo e o pior inimigo de mortos-vivos e criaturas do Véu.',
    fis: { massaBase: 74, alcance: 1.05, tolFrio: 1.1, tolCalor: 1.1 },
    tags: ['cura_ampliada', 'luz_propria', 'resist_sombra'], visual: { auraLuz: true, olhosBrilhantes: true, halo: true },
  },
  kenku: {
    nome: 'Kenku', mods: { destreza: 3, intelecto: 1, espirito: 1, carisma: -2 },
    altura: [1.45, 1.7], peso: [35, 55], cores: ['#2a2a32', '#3a3a44', '#4a4438', '#1f1f26'],
    passiva: 'Mímica Perfeita: copia qualquer som ou voz que já ouviu — o Mestre IA aceita distração, imitação e engano como mecanismo válido. +25% de dano furtivo.',
    desc: 'Corvos humanoides amaldiçoados: perderam a voz própria e as asas, restou a imitação perfeita. A raça mais forte no sistema de argumentação criativa — enganar é um mecanismo físico legítimo.',
    fis: { massaBase: 44, alcance: 0.95, tolFrio: 0.9, tolCalor: 0.95 },
    tags: ['mimica', 'furtivo', 'leve'], visual: { bico: true, penas: true, olhosSemPupila: true },
  },
  tortle: {
    nome: 'Tortle', mods: { vigor: 4, forca: 1, espirito: 1, destreza: -3 },
    altura: [1.5, 1.8], peso: [110, 180], cores: ['#6a7a4a', '#7a8a5a', '#5a6a42', '#8a7a52'],
    passiva: 'Casco Natural: +35% de armadura permanente. Recolher-se no casco (defesa total, imobilizado). Prende a respiração por minutos.',
    desc: 'Tartarugas humanoides, pacientes e praticamente inquebráveis. A armadura natural mais alta do jogo — pagando com a pior destreza. Estratégia de tanque puro: você não desvia, você absorve.',
    fis: { massaBase: 140, alcance: 0.95, tolFrio: 1.2, tolCalor: 1.2 },
    tags: ['casco', 'folego', 'lento'], visual: { casco: true, focinho: true, escamas: true },
  },
  leonin: {
    nome: 'Leonin', mods: { forca: 3, vigor: 2, carisma: 1, intelecto: -2 },
    altura: [1.85, 2.2], peso: [100, 165], cores: ['#d8a860', '#c89050', '#b88048', '#e0b878'],
    passiva: 'Rugido Aterrorizante: cone que aplica medo em área (cooldown). Garras naturais: ataque físico +40% e conta como arma mágica.',
    desc: 'Povo leão, orgulhoso e territorial. Predadores de emboscada com força de investida brutal. As garras dispensam arma e o rugido quebra formações inimigas antes do choque.',
    fis: { massaBase: 130, alcance: 1.18, tolFrio: 1.0, tolCalor: 1.3 },
    tags: ['rugido', 'garras', 'visao_noturna'], visual: { focinho: true, juba: true, orelhasAnimais: 'felinas', cauda: true, pelagem: true, musculoso: true },
  },
  warforged: {
    nome: 'Warforged', mods: { vigor: 4, forca: 2, espirito: 1, carisma: -3, destreza: -1 },
    altura: [1.8, 2.3], peso: [180, 320], cores: ['#8d8d96', '#6b5a48', '#3f4a55', '#a09080'],
    passiva: 'Construto Vivo: imune a veneno, doença e sufocamento; não precisa dormir nem comer. NÃO regenera vida naturalmente (só por reparo) e AFUNDA em água profunda.',
    desc: 'Construtos mecânicos sencientes, forjados para uma guerra que já acabou. Jogam com regras diferentes: cura orgânica não funciona, mas veneno também não. Massa de até 320 kg quebra pisos frágeis e ignora empurrões — e transforma qualquer corpo d\'água numa armadilha mortal.',
    fis: { massaBase: 240, alcance: 1.2, tolFrio: 1.6, tolCalor: 0.7 },
    tags: ['construto', 'inabalavel', 'imune_veneno', 'afunda', 'grande', 'metalico'], visual: { nucleo: true, placas: true, juntas: true, olhosBrilhantes: true },
  },
};

export const ORIGENS = {
  aldeao:    { nome: 'Aldeão Sobrevivente', bonus: { vigor: 1, carisma: 1 }, item: 'Foice gasta', desc: 'Conhece plantio, clima e como consertar coisas com pouco. Perícia: Sobrevivência.' },
  academico: { nome: 'Acadêmico da Torre',  bonus: { intelecto: 2 }, item: 'Grimório rasgado', desc: 'Sabe química, alavancas, densidade e o nome verdadeiro das coisas. Perícia: Arcana + Ciências.' },
  soldado:   { nome: 'Veterano de Guerra',  bonus: { forca: 1, vigor: 1 }, item: 'Espada de serviço', desc: 'Tática, formações, ferimentos. Perícia: Combate + Medicina de campo.' },
  ladrao:    { nome: 'Dedos Leves',         bonus: { destreza: 2 }, item: 'Adagas gêmeas', desc: 'Fechaduras, sombras, pontos fracos estruturais. Perícia: Furtividade + Engenharia improvisada.' },
  ermitao:   { nome: 'Ermitão do Véu',      bonus: { espirito: 2 }, item: 'Totem de osso', desc: 'Sonhos proféticos e conversas com coisas que não deveriam falar. Perícia: Ocultismo.' },
  ferreiro:  { nome: 'Ferreiro Rúnico',     bonus: { forca: 1, intelecto: 1 }, item: 'Martelo rúnico', desc: 'Metalurgia, temperaturas de fusão, encantamento. Perícia: Artesanato.' },
};

export const CLASSES = {
  barbaro: {
    nome: 'Bárbaro', recurso: 'Fúria', prim: 'forca',
    desc: 'Guerreiro brutal que entra em fúria. Enquanto enfurecido: +60% de dano físico, -50% de dano recebido e imunidade a medo — mas você NÃO consegue conjurar magia. Quanto menos vida, mais forte fica.',
    vida: 1.7, mana: 0.3, stam: 1.6, escolas: 0, arma: 'machado',
    mecanica: 'Fúria dura 15 s e é alimentada por dano recebido. Massa corporal alta aumenta o dano de investida (p = m·v).',
    tags: ['furia', 'sem_magia', 'tanque'],
  },
  bardo: {
    nome: 'Bardo', recurso: 'Inspiração', prim: 'carisma',
    desc: 'Músico manipulador e usuário de magia. Suas canções aplicam buffs em área a aliados e debuffs em inimigos. No multiplayer é a classe mais valiosa de um grupo.',
    vida: 1.1, mana: 1.3, stam: 1.1, escolas: 2, arma: 'alaude',
    mecanica: 'Som é vibração: o Mestre IA aceita ressonância, frequência e fratura acústica como mecanismo. Canções não funcionam em construtos surdos nem no vácuo.',
    tags: ['suporte', 'area', 'social'],
  },
  bruxo: {
    nome: 'Bruxo', recurso: 'Pacto', prim: 'carisma',
    desc: 'Fez um pacto com uma entidade poderosa. Poucos slots de magia, mas cada conjuração é devastadora e recarrega rápido. Seu patrono ocasionalmente INTERVÉM — para ajudar ou cobrar.',
    vida: 1.0, mana: 1.2, stam: 1.0, escolas: 2, arma: 'grimorio',
    mecanica: 'Custo de mana -35%, cooldowns -25%, mas mana máxima -30%. Perto do Véu o patrono fica mais ativo (bônus e riscos dobrados).',
    tags: ['pacto', 'burst', 'veu'],
  },
  clerigo: {
    nome: 'Clérigo', recurso: 'Fé', prim: 'espirito',
    desc: 'Usuário de magia divina: cura, escudos e dano radiante. A única classe que ressuscita aliados caídos no multiplayer.',
    vida: 1.3, mana: 1.35, stam: 1.0, escolas: 2, arma: 'maca',
    mecanica: 'Curas +40%. Vitalurgia não funciona em construtos — contra Warforged aliados você precisa de reparo, não cura.',
    tags: ['cura', 'suporte', 'radiante'],
  },
  druida: {
    nome: 'Druida', recurso: 'Vínculo Natural', prim: 'espirito',
    desc: 'Controla a natureza e se transforma em animal. A Forma Selvagem troca sua ficha inteira: massa, velocidade, garras e sentidos do animal escolhido.',
    vida: 1.2, mana: 1.4, stam: 1.2, escolas: 2, arma: 'cajado_natural',
    mecanica: 'Forma de Urso (+massa, +armadura), Lobo (+velocidade), Águia (voo). A massa muda de verdade: como urso você ignora rajadas; como águia o vento te leva.',
    tags: ['forma_selvagem', 'natureza', 'versatil'],
  },
  feiticeiro: {
    nome: 'Feiticeiro', recurso: 'Fonte Arcana', prim: 'carisma',
    desc: 'Nasceu com magia no sangue — não estudou, simplesmente tem. Pode METAMAGIAR: gastar mana extra para ampliar, acelerar, dividir ou empurrar qualquer feitiço.',
    vida: 0.9, mana: 1.55, stam: 0.9, escolas: 2, arma: 'foco_cristal',
    mecanica: 'Metamagia: segure SHIFT ao conjurar para dobrar o custo e o raio/dano. Magia instintiva é imprevisível: 4% de chance de surto arcano.',
    tags: ['metamagia', 'nuker', 'instintivo'],
  },
  guerreiro: {
    nome: 'Guerreiro', recurso: 'Fôlego', prim: 'forca',
    desc: 'Especialista em combate. Domina todas as armas e armaduras, tem o maior número de ataques por segundo e pode INTERROMPER conjurações inimigas com um golpe bem colocado.',
    vida: 1.5, mana: 0.6, stam: 1.5, escolas: 1, arma: 'espada',
    mecanica: 'Armadura pesada = você é metálico: raio causa +60% em você, mas sua armadura absorve 25% do dano físico. Retomar Fôlego cura 25% da vida (1×/combate).',
    tags: ['marcial', 'metalico', 'interromper'],
  },
  ladino: {
    nome: 'Ladino', recurso: 'Foco', prim: 'destreza',
    desc: 'Furtividade e dano crítico. Ataques pelas costas ou contra alvos desprevenidos causam DANO FURTIVO massivo. Abre fechaduras, desarma armadilhas e encontra os pontos frágeis de qualquer estrutura.',
    vida: 1.0, mana: 0.9, stam: 1.4, escolas: 1, arma: 'adagas',
    mecanica: 'Dano furtivo ×3 por trás. O Mestre IA reconhece "ponto estrutural fraco" como argumento automático para você — você VÊ onde as coisas quebram.',
    tags: ['furtivo', 'critico', 'estruturas'],
  },
  monge: {
    nome: 'Monge', recurso: 'Ki', prim: 'destreza',
    desc: 'Artes marciais e energia espiritual. Rajada de golpes, corrida em paredes, queda lenta e desvio de projéteis — pode inclusive PEGAR um projétil no ar e devolvê-lo.',
    vida: 1.15, mana: 1.0, stam: 1.6, escolas: 1, arma: 'punhos',
    mecanica: 'Sem armadura, mas +2 m/s de velocidade e imunidade a dano de queda. Devolver projétil usa o momento linear original (p = m·v) contra o lançador.',
    tags: ['marcial', 'mobilidade', 'cai_de_pe', 'desarmado'],
  },
  paladino: {
    nome: 'Paladino', recurso: 'Juramento', prim: 'forca',
    desc: 'Guerreiro sagrado. Canaliza poder divino pelas próprias mãos: Punição Divina adiciona dano radiante explosivo ao golpe, e sua aura protege aliados próximos.',
    vida: 1.45, mana: 1.0, stam: 1.3, escolas: 1, arma: 'espada_sagrada',
    mecanica: 'Aura de 10 m: aliados recebem -20% de dano. Imposição de Mãos cura por contato. Quebrar o juramento (atacar aliado) desativa tudo por 60 s.',
    tags: ['marcial', 'aura', 'radiante', 'metalico'],
  },
  patrulheiro: {
    nome: 'Patrulheiro', recurso: 'Foco Natural', prim: 'destreza',
    desc: 'Caçador e sobrevivente. Melhor alcance do jogo, rastreia criaturas pelo mapa, monta armadilhas e ignora terreno difícil. Tem um inimigo predileto com dano bônus permanente.',
    vida: 1.15, mana: 1.05, stam: 1.35, escolas: 1, arma: 'arco',
    mecanica: 'Flechas são balística real: alcance = v²/g e você compensa a queda automaticamente. Ignora a penalidade de atrito de pântano e neve.',
    tags: ['distancia', 'rastreio', 'armadilhas', 'terreno'],
  },
  mago: {
    nome: 'Mago', recurso: 'Mana', prim: 'intelecto',
    desc: 'Mestre da magia estudada. O maior poder mágico bruto e o único que COMBINA duas escolas num único feitiço (vapor = fogo + água; tempestade = água + raio). Corpo frágil.',
    vida: 0.85, mana: 1.65, stam: 0.9, escolas: 3, arma: 'cajado',
    mecanica: 'Ritual: conjure fora de combate por 1/3 do custo. O Mestre IA dá +2 extra a magos em qualquer argumento que cite física ou química real — você estudou isso.',
    tags: ['nuker', 'combo_escolas', 'erudito'],
  },
};

// --- Escolas de magia: cada uma com regra física explícita -----------------
export const ESCOLAS = {
  fogo: {
    nome: 'Piromancia', cor: '#ff6a2a',
    fisica: 'Calor. Precisa de combustível e oxigênio: dobra de dano em floresta seca e contra teias de óleo, falha debaixo d\'água ou na chuva forte. Aquece metal (armaduras viram armadilhas) e cria correntes de ar ascendentes que você pode usar para planar.',
    magias: ['brasa', 'lanca_fogo', 'explosao', 'muro_chamas'],
  },
  agua: {
    nome: 'Hidromancia', cor: '#3aa6ff',
    fisica: 'Massa e pressão. Água pesa 1 kg/litro: o volume que você move é limitado pelo seu Intelecto. Congela a 0 °C (pontes, prisões), conduz eletricidade e apaga fogo. Em desertos você precisa extrair umidade do ar — custo triplicado.',
    magias: ['jato', 'prisao_gelo', 'onda', 'ponte_gelo'],
  },
  ar: {
    nome: 'Aeromancia', cor: '#b9e3ff',
    fisica: 'Força vetorial. Empurrão real: a aceleração aplicada depende da MASSA do alvo. Um feérico voa longe, um golem nem se move. Cria vácuo (sufoca), reduz atrito e permite saltos duplos.',
    magias: ['rajada', 'salto_vento', 'vacuo', 'lamina_ar'],
  },
  terra: {
    nome: 'Geomancia', cor: '#b98a4a',
    fisica: 'Estrutura e gravidade. Você não cria matéria: molda a que existe. Precisa de solo/rocha por perto. Muros erguidos podem desabar sobre você se mal apoiados — o motor simula o colapso.',
    magias: ['muro_pedra', 'lanca_pedra', 'tremor', 'pele_pedra'],
  },
  raio: {
    nome: 'Fulguromancia', cor: '#ffe14a',
    fisica: 'Eletricidade busca o caminho de menor resistência. Salta entre alvos molhados ou de armadura metálica, é absorvido por terra/borracha, e paralisa músculos (stun) antes de queimar.',
    magias: ['choque', 'corrente', 'tempestade', 'passo_relampago'],
  },
  vida: {
    nome: 'Vitalurgia', cor: '#67e58a',
    fisica: 'Reorganiza matéria orgânica. Cura acelera processos naturais — não recria membros nem funciona em construtos. Cada cura tem custo metabólico: o alvo sente fome e fadiga depois.',
    magias: ['curar', 'regeneracao', 'raizes', 'purificar'],
  },
  sombra: {
    nome: 'Umbramancia', cor: '#8a5cd8',
    fisica: 'Manipula luz e percepção. Invisibilidade é refração: você ainda faz som, deixa pegadas e desloca ar. Precisa de sombra para teleporte curto. Em pleno sol, custo dobrado.',
    magias: ['manto_sombra', 'passo_sombrio', 'garra_negra', 'medo'],
  },
  runica: {
    nome: 'Runologia', cor: '#d9b3ff',
    fisica: 'Magia gravada: efeito retardado com condição de disparo. Você desenha a runa (leva tempo, fica visível) e ela dispara quando a condição ocorre. A base das armadilhas e das defesas de base.',
    magias: ['runa_explosiva', 'runa_escudo', 'runa_teleporte', 'runa_amplificacao'],
  },
};

export const MAGIAS = {
  brasa:            { nome: 'Brasa',                escola: 'fogo',   custo: 6,  dano: 14, cd: 0.5, tipo: 'projetil', vel: 40, desc: 'Projétil rápido e barato. Incendeia alvos secos.' },
  lanca_fogo:       { nome: 'Lança Flamejante',     escola: 'fogo',   custo: 18, dano: 42, cd: 2.0, tipo: 'projetil', vel: 55, desc: 'Perfura e continua queimando (dano por tempo).' },
  explosao:         { nome: 'Detonação',            escola: 'fogo',   custo: 34, dano: 60, cd: 5.0, tipo: 'area', raio: 8, desc: 'Explosão em área. Onda de choque empurra por massa.' },
  muro_chamas:      { nome: 'Muro de Chamas',       escola: 'fogo',   custo: 28, dano: 18, cd: 8.0, tipo: 'muro', desc: 'Barreira de fogo. Consome oxigênio em espaços fechados.' },
  jato:             { nome: 'Jato Pressurizado',    escola: 'agua',   custo: 9,  dano: 18, cd: 0.7, tipo: 'projetil', vel: 45, desc: 'Corta e empurra. Apaga fogo.' },
  prisao_gelo:      { nome: 'Prisão de Gelo',       escola: 'agua',   custo: 24, dano: 12, cd: 6.0, tipo: 'controle', desc: 'Congela o alvo. Quebra com dano físico ou calor.' },
  onda:             { nome: 'Maremoto',             escola: 'agua',   custo: 38, dano: 34, cd: 9.0, tipo: 'area', raio: 12, desc: 'Empurra em massa e molha tudo (sinergia com raio).' },
  ponte_gelo:       { nome: 'Ponte de Gelo',        escola: 'agua',   custo: 20, dano: 0,  cd: 5.0, tipo: 'utilidade', desc: 'Cria plataforma sólida. Suporta peso limitado.' },
  rajada:           { nome: 'Rajada',               escola: 'ar',     custo: 7,  dano: 10, cd: 0.6, tipo: 'projetil', vel: 60, desc: 'Empurrão proporcional ao inverso da massa do alvo.' },
  salto_vento:      { nome: 'Salto do Vento',       escola: 'ar',     custo: 14, dano: 0,  cd: 2.5, tipo: 'mobilidade', desc: 'Impulso vertical. Quanto mais leve você for, mais alto.' },
  vacuo:            { nome: 'Vácuo',                escola: 'ar',     custo: 30, dano: 26, cd: 7.0, tipo: 'area', raio: 7, desc: 'Suga o ar: sufoca e apaga chamas.' },
  lamina_ar:        { nome: 'Lâmina de Ar',         escola: 'ar',     custo: 20, dano: 38, cd: 2.2, tipo: 'projetil', vel: 80, desc: 'Corte invisível de alta velocidade.' },
  muro_pedra:       { nome: 'Muro de Pedra',        escola: 'terra',  custo: 22, dano: 0,  cd: 5.0, tipo: 'utilidade', desc: 'Ergue cobertura sólida do solo. Colapsável.' },
  lanca_pedra:      { nome: 'Lança de Pedra',       escola: 'terra',  custo: 12, dano: 28, cd: 1.2, tipo: 'projetil', vel: 35, desc: 'Massa alta: dano por impacto, queda balística.' },
  tremor:           { nome: 'Tremor',               escola: 'terra',  custo: 32, dano: 40, cd: 8.0, tipo: 'area', raio: 10, desc: 'Derruba alvos no chão e desestabiliza estruturas.' },
  pele_pedra:       { nome: 'Pele de Pedra',        escola: 'terra',  custo: 20, dano: 0,  cd: 12,  tipo: 'buff', desc: '+60% armadura, -30% velocidade (massa aumenta).' },
  choque:           { nome: 'Choque',               escola: 'raio',   custo: 8,  dano: 16, cd: 0.6, tipo: 'projetil', vel: 90, desc: 'Instantâneo. Stun curto.' },
  corrente:         { nome: 'Corrente Elétrica',    escola: 'raio',   custo: 22, dano: 30, cd: 3.0, tipo: 'cadeia', desc: 'Salta entre alvos molhados/metálicos.' },
  tempestade:       { nome: 'Tempestade',           escola: 'raio',   custo: 44, dano: 22, cd: 14,  tipo: 'area', raio: 14, desc: 'Raios contínuos na área. Devastador na chuva.' },
  passo_relampago:  { nome: 'Passo Relâmpago',      escola: 'raio',   custo: 16, dano: 0,  cd: 3.0, tipo: 'mobilidade', desc: 'Dash elétrico atravessando inimigos.' },
  curar:            { nome: 'Curar',                escola: 'vida',   custo: 18, dano: -45, cd: 2.0, tipo: 'cura', desc: 'Restaura vida. Não funciona em construtos.' },
  regeneracao:      { nome: 'Regeneração',          escola: 'vida',   custo: 26, dano: -8, cd: 10,  tipo: 'buff', desc: 'Cura contínua por 20s.' },
  raizes:           { nome: 'Raízes',               escola: 'vida',   custo: 16, dano: 6,  cd: 5.0, tipo: 'controle', desc: 'Prende ao solo. Inútil em pedra pura.' },
  purificar:        { nome: 'Purificar',            escola: 'vida',   custo: 14, dano: 0,  cd: 6.0, tipo: 'utilidade', desc: 'Remove veneno, queimadura e maldição.' },
  manto_sombra:     { nome: 'Manto de Sombras',     escola: 'sombra', custo: 22, dano: 0,  cd: 10,  tipo: 'buff', desc: 'Quase invisível parado; o movimento revela.' },
  passo_sombrio:    { nome: 'Passo Sombrio',        escola: 'sombra', custo: 18, dano: 0,  cd: 4.0, tipo: 'mobilidade', desc: 'Teleporte curto entre sombras.' },
  garra_negra:      { nome: 'Garra Negra',          escola: 'sombra', custo: 15, dano: 34, cd: 1.5, tipo: 'projetil', vel: 50, desc: 'Dano que ignora armadura física.' },
  medo:             { nome: 'Terror',               escola: 'sombra', custo: 26, dano: 0,  cd: 9.0, tipo: 'controle', desc: 'Inimigos fogem. Chefes resistem.' },
  runa_explosiva:   { nome: 'Runa Explosiva',       escola: 'runica', custo: 20, dano: 55, cd: 4.0, tipo: 'armadilha', desc: 'Detona por proximidade. Some no chão.' },
  runa_escudo:      { nome: 'Runa de Escudo',       escola: 'runica', custo: 24, dano: 0,  cd: 8.0, tipo: 'buff', desc: 'Barreira que absorve dano fixo.' },
  runa_teleporte:   { nome: 'Runa de Retorno',      escola: 'runica', custo: 30, dano: 0,  cd: 20,  tipo: 'utilidade', desc: 'Marca um ponto; volte a ele depois.' },
  runa_amplificacao:{ nome: 'Runa de Amplificação', escola: 'runica', custo: 28, dano: 0,  cd: 15,  tipo: 'buff', desc: 'Próximas 3 magias custam -50% e causam +40%.' },
};

export const TRACOS = {
  pirofobia:     { nome: 'Pirofobia',        tipo: 'defeito', desc: 'Pânico perto de fogo grande: -20% precisão. Ganha 2 pontos extras.', pts: 2 },
  sangue_frio:   { nome: 'Sangue-Frio',      tipo: 'virtude', desc: 'Imune a medo, +15% dano com pouca vida.', pts: -2 },
  memoria_total: { nome: 'Memória Eidética', tipo: 'virtude', desc: 'O Mestre IA aceita referências a fatos vistos há muito tempo; +1 relance em argumentos.', pts: -3 },
  maldicao_veu:  { nome: 'Marcado pelo Véu', tipo: 'misto',   desc: '+25% mana máxima, mas 5% de chance de falha caótica em cada magia.', pts: 0 },
  peso_leve:     { nome: 'Ossos Ocos',       tipo: 'misto',   desc: '-25% massa: pula mais, é empurrado mais longe.', pts: 0 },
  cicatrizes:    { nome: 'Coberto de Cicatrizes', tipo: 'virtude', desc: '+15% vida máxima, -1 Carisma.', pts: -1 },
  mao_firme:     { nome: 'Mão Firme',        tipo: 'virtude', desc: 'Conjuração não é interrompida por dano leve.', pts: -2 },
  falastrao:     { nome: 'Falastrão',        tipo: 'defeito', desc: 'Inimigos te notam 40% mais longe. Ganha 2 pontos.', pts: 2 },
};

export const CORPO = {
  altura:   { min: 1.1, max: 2.6, step: 0.01, label: 'Altura (m)', desc: 'Afeta alcance, altura de pulo, hitbox e o quanto você cabe em passagens estreitas.' },
  massa:    { min: 25, max: 400, step: 1, label: 'Massa (kg)', desc: 'Inércia real: define quanto o vento te move, o dano de queda e se pisos frágeis quebram.' },
  musculo:  { min: 0, max: 100, step: 1, label: 'Musculatura', desc: 'Divide sua massa entre músculo e gordura. Músculo = força; gordura = isolamento térmico.' },
  ombros:   { min: 0, max: 100, step: 1, label: 'Largura dos ombros', desc: 'Visual + hitbox horizontal.' },
};

export const PONTOS_INICIAIS = 12;
export const ATTR_BASE = 8;
